name: Trigger the 'postman-workflow-smoke-cron-trigger-test' Test Workflow on Testkube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: kubeshop/setup-testkube@v1
      with:
        organization: ${{ secrets.TESTKUBE_ORG_ID }}
        environment: ${{ secrets.TESTKUBE_ENV_ID }}
        token: ${{ secrets.TESTKUBE_TOKEN }}
        url: testkube.dev
    - run: |
        testkube run testworkflow postman-workflow-smoke-cron-trigger-test -f
