name: Trigger Testkube Test

on: 
  pull_request:
    branches: [main]

jobs: 
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: kubeshop/setup-testkube@v1
      with:
        organization: ${{ secrets.TESTKUBE_ORG_ID }}
        environment: ${{ secrets.TESTKUBE_ENV_ID }}
        token: ${{ secrets.TESTKUBE_TOKEN }}
        url: testkube.dev
    - run: |
        testkube run test curl-test1 -f
